name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main # Adjust if your primary branch is named differently (NO NEED TO ADJUST FOR NOW)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Checks out your repository under $GITHUB_WORKSPACE

    - name: Deploy to Lightsail
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USERNAME }}
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          sudo apt-get update
          sudo apt-get install -y nginx
          sudo systemctl stop nginx
          rm -rf /var/www/html/*
          cp -r * /var/www/html/
          sudo systemctl start nginx
          curl http://siningwang.com
